spring.application.name=${APP_NAME:bibflip-eureka}

server.port=${SERVER_PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}

##Como este proyecto ES el servidor Eureka, no debe registrarse a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

##URL del propio servidor Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://${eureka.instance.hostname}:${server.port}/eureka/}